### ISSUE TITLE
How to get an unencoded frame?

### ISSUE THREAD

**Issue by qdlmcfresh** [robmikh/displayrecorder#5]
Hi, im trying to add a directx display/windowcapturer to https://github.com/H-M-H/Weylus  
Since encoding is handled already i only need a bgr8 slice of the unencoded frame. 
Before you pointed me to this repo i tried the same with [screenshot-rs](https://github.com/robmikh/screenshot-rs) and it worked, but i dont know how to get the data i need here.

**Comment by robmikh** [comment]
You'll need to refer to screenshot-rs for that. Because Media Foundation does all the heavy lifting and encodes on the GPU, displayrecorder never copies the bits into system memory.

In short, you'll need to:

- Create a staging texture 
- Copy the frame texture into the staging texture
- Map the staging texture
- Get a slice from the d3d mapped struct (refer to screenshot-rs)
- (Optional) copy the bytes out
- Unmap the staging texture
